{VCL2FMX Â© 2026 echurchsites.wixsite.com
 FMXMessageBridge.pas â€” Cross-platform message bridge
 Generated by VCL2FMX Converter v4.1
 Replaces Windows WM_USER messaging with TMessageManager.}

unit FMXMessageBridge;

{ PURPOSE
  This unit provides a cross-platform alternative to Windows WM_USER
  messaging. It uses Embarcadero's TMessageManager (System.Messaging)
  which works identically on Windows, macOS, iOS, and Android.

  QUICK START
  1. Define a typed message for each WM_USER + N you had:
       type TMyCustomMsg = class(TMessage<Integer>) end;

  2. In FormCreate, subscribe:
       TMessageManager.DefaultManager.SubscribeToMessage(TMyCustomMsg,
         procedure(const Sender: TObject; const M: TMessage)
         begin
           HandleMyCustomMsg(M as TMyCustomMsg);
         end);

  3. To send (replaces PostMessage/SendMessage):
       TMessageManager.DefaultManager.SendMessage(Self,
         TMyCustomMsg.Create(YourIntegerValue));

  4. In FormDestroy, unsubscribe:
       TMessageManager.DefaultManager.Unsubscribe(TMyCustomMsg);

  NOTE: TMessage<T> is generic. Use any payload type:
    TMessage<string>, TMessage<TObject>, TMessage<Integer>, etc.
    Or define a payload record for complex data.}

interface

uses
  System.Messaging,
  System.SysUtils,
  System.Classes;

type
  { Base class for all converted WM_USER messages.
    Subclass this for each distinct message type. }
  TFMXUserMessage = class(TMessage<Integer>)
  public
    constructor Create(const AValue: Integer = 0); reintroduce;
  end;

  { Generic helper: send a message to all subscribers. }
  procedure FMXSendMessage(AMsgClass: TClass; AValue: Integer = 0);

  { Generic helper: post a message asynchronously via main thread. }
  procedure FMXPostMessage(AMsgClass: TClass; AValue: Integer = 0);

implementation

constructor TFMXUserMessage.Create(const AValue: Integer = 0);
begin
  inherited Create(AValue);
end;

procedure FMXSendMessage(AMsgClass: TClass; AValue: Integer = 0);
begin
  TMessageManager.DefaultManager.SendMessage(nil,
    TFMXUserMessage.Create(AValue));
end;

procedure FMXPostMessage(AMsgClass: TClass; AValue: Integer = 0);
begin
  TThread.Queue(nil,
    procedure
    begin
      TMessageManager.DefaultManager.SendMessage(nil,
        TFMXUserMessage.Create(AValue));
    end);
end;

end.
